#ifndef TI_ALLOC_CONST_H
#define TI_ALLOC_CONST_H

// #define TI_DMALLOC_ENABLE_TRACE

#define TI_DMALLOC_PAGE_SIZE (0x1000ULL)
#define TI_DMALLOC_STACK_DEPTH (32ULL)
#define TI_DMALLOC_STACK_CAPACITY (0x32ULL)

#endif // TI_ALLOC_CONST_H
