#ifndef TI_TREE_CONST_H
#define TI_TREE_CONST_H

#define TI_TRIE_NODE_CHILD_COUNT (0x100)
#define TI_TRIE_NODE_POOL_CAPACITY (0x400)
#define TI_TRIE_NODE_POOL_ALIGNMENT (0x10)

#endif // TI_TREE_CONST_H
