#ifndef TI_CONST_H
#define TI_CONST_H

// #define TI_DMALLOC_ENABLE_TRACE

#define TI_DMALLOC_PAGE_SIZE (4096ULL)
#define TI_DMALLOC_STACK_DEPTH (32ULL)
#define TI_DMALLOC_STACK_CAPACITY (32ULL)

#define TI_PATH_SIZE (256ULL)

#define TI_MAP_TABLE_CAPACITY (128ULL)
#define TI_MAP_POOL_CAPACITY (1024ULL)
#define TI_MAP_LOAD_FACTOR (75ULL)

#endif // TI_CONST_H
