#ifndef TI_VK_CONST_H
#define TI_VK_CONST_H

#define TI_VENDOR_ID_NVIDIA (0x10DE)
#define TI_VENDOR_ID_AMD (0x1002)
#define TI_VENDOR_ID_INTEL (0x8086)

#define TI_MAX_SURFACE_FORMATS (0xFF)
#define TI_MAX_PRESENT_MODES (0xFF)

#define TI_WINDOW_MAX_DELTA_TIME (0.1F)
#define TI_WINDOW_MAX_PHYSICAL_DEVICES (0x10)
#define TI_WINDOW_MAX_QUEUE_FAMILY_PROPERTIES_COUNT (0xFF)
#define TI_WINDOW_MAX_EXTENSION_PROPERTIES_COUNT (0x400)

#define TI_SWAPCHAIN_MAX_IMAGE_COUNT (0x10)

#define TI_DEBUG_LINE_VERTEX_COUNT (0xFFFFF)
#define TI_DEBUG_LINE_INDEX_COUNT (0xFFFFF)

#endif // TI_VK_CONST_H
