#ifndef TI_VULKAN_WINDOW_H
#define TI_VULKAN_WINDOW_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern VkPhysicalDeviceRayTracingPipelinePropertiesKHR g_physical_device_ray_tracing_pipeline_properties;

extern VkPhysicalDeviceVulkan12Features g_physical_device_vulkan_12_features;
extern VkPhysicalDeviceRayTracingPipelineFeaturesKHR g_physical_device_ray_tracing_pipeline_features;
extern VkPhysicalDeviceAccelerationStructureFeaturesKHR g_physical_device_acceleration_structure_features;
extern VkPhysicalDeviceMaintenance4Features g_physical_device_maintenance_4_features;
extern VkPhysicalDeviceFragmentShadingRateFeaturesKHR g_physical_device_fragment_shading_rate_features;
extern VkPhysicalDeviceMultiviewFeatures g_physical_device_multiview_features;
extern VkPhysicalDeviceMeshShaderFeaturesEXT g_physical_device_mesh_shader_features;

extern window_t g_window;

#ifdef BUILD_DEBUG
extern PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT_proc;
extern PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT_proc;
#endif // BUILD_DEBUG

extern PFN_vkCmdDrawMeshTasksEXT vkCmdDrawMeshTasksEXT_proc;
extern PFN_vkCmdTraceRaysKHR vkCmdTraceRaysKHR_proc;
extern PFN_vkCmdBuildAccelerationStructuresKHR vkCmdBuildAccelerationStructuresKHR_proc;

extern PFN_vkCreateAccelerationStructureKHR vkCreateAccelerationStructureKHR_proc;
extern PFN_vkCreateRayTracingPipelinesKHR vkCreateRayTracingPipelinesKHR_proc;

extern PFN_vkGetAccelerationStructureBuildSizesKHR vkGetAccelerationStructureBuildSizesKHR_proc;
extern PFN_vkGetAccelerationStructureDeviceAddressKHR vkGetAccelerationStructureDeviceAddressKHR_proc;
extern PFN_vkGetRayTracingShaderGroupHandlesKHR vkGetRayTracingShaderGroupHandlesKHR_proc;

extern PFN_vkDestroyAccelerationStructureKHR vkDestroyAccelerationStructureKHR_proc;

void window_create(uint32_t width, uint32_t height, char const *title);
void window_run(void);
void window_destroy(void);

uint32_t window_is_keyboard_key_pressed(keyboard_key_t key);
uint32_t window_is_keyboard_key_held(keyboard_key_t key);
uint32_t window_is_keyboard_key_released(keyboard_key_t key);

uint32_t window_is_mouse_key_pressed(mouse_key_t key);
uint32_t window_is_mouse_key_held(mouse_key_t key);
uint32_t window_is_mouse_key_released(mouse_key_t key);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // TI_VULKAN_WINDOW_H
